# Generated by Django 5.0.3 on 2024-03-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='order_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
